services:
  - type: web
    name: sfh-web-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    buildCommand: |
      docker build -t sfh-web-app .
    startCommand: nginx -g "daemon off;"
    staticPublishPath: /usr/share/nginx/html